# Generated by Django 4.0.1 on 2022-02-01 00:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question', models.TextField(verbose_name='Question')),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expert', 'Expert'), ('Prodigy', 'Prodigy')], max_length=13, verbose_name='Difficulty level')),
                ('sample_input', models.TextField(verbose_name='Sample Input')),
                ('sample_output', models.TextField(verbose_name='Sample Output')),
                ('question_id', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=5, populate_from=['question', 'difficulty_level'], primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('solution', models.TextField(verbose_name='Write your code here')),
                ('output', models.TextField(blank=True, verbose_name='Your output')),
                ('answer_id', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=10, populate_from=['solution'], primary_key=True, serialize=False, unique=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Solutions.question')),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_score', models.IntegerField(default=0, verbose_name='Your score')),
                ('user_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='Solutions.useranswer')),
            ],
        ),
    ]
